"""
NEXORA ATLAS - Intelligence Engine Domain Types & Enums
"""

from enum import Enum


class Severity(str, Enum):
    INFO = "INFO"
    LOW = "LOW"
    MEDIUM = "MEDIUM"
    HIGH = "HIGH"
    CRITICAL = "CRITICAL"


class RiskLevel(str, Enum):
    NONE = "NONE"
    LOW = "LOW"
    MEDIUM = "MEDIUM"
    HIGH = "HIGH"


class RuleStatus(str, Enum):
    EVALUATED_VIOLATION = "EVALUATED_VIOLATION"
    EVALUATED_CLEAN = "EVALUATED_CLEAN"
    SKIPPED = "SKIPPED"


class WasteType(str, Enum):
    IDLE_COMPUTE = "IDLE_COMPUTE"
    OVERSIZED_INSTANCE = "OVERSIZED_INSTANCE"
    UNATTACHED_VOLUME = "UNATTACHED_VOLUME"
    IDLE_DATABASE = "IDLE_DATABASE"
    LEGACY_STORAGE_TIER = "LEGACY_STORAGE_TIER"
    UNASSOCIATED_EIP = "UNASSOCIATED_EIP"
    UNMANAGED_OBJECT_VERSIONS = "UNMANAGED_OBJECT_VERSIONS"
    OFF_HOURS_IDLE = "OFF_HOURS_IDLE"


class AnomalyRuleType(str, Enum):
    COST_SPIKE = "COST_SPIKE"
    SUSTAINED_INCREASE = "SUSTAINED_INCREASE"
    RESOURCE_OUTLIER = "RESOURCE_OUTLIER"
    ACCOUNT_SHIFT = "ACCOUNT_SHIFT"


class EvidenceType(str, Enum):
    COST = "COST"
    UTILIZATION = "UTILIZATION"
    RESOURCE_STATE = "RESOURCE_STATE"
    RESOURCE_CONFIGURATION = "RESOURCE_CONFIGURATION"
    TAG = "TAG"
    DURATION = "DURATION"
    ACCOUNT = "ACCOUNT"
    SERVICE = "SERVICE"
