"""initial_schema

Revision ID: 4b0cbd317c07
Revises: 
Create Date: 2026-09-16 14:20:11.728261

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4b0cbd317c07'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cloud_regions',
    sa.Column('provider_type', sa.String(length=50), nullable=False),
    sa.Column('region_code', sa.String(length=50), nullable=False),
    sa.Column('display_name', sa.String(length=100), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider_type', 'region_code', name='uq_region_provider_code')
    )
    op.create_index(op.f('ix_cloud_regions_id'), 'cloud_regions', ['id'], unique=False)
    op.create_table('organizations',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('timezone', sa.String(length=50), nullable=False),
    sa.Column('is_demo', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_organizations_id'), 'organizations', ['id'], unique=False)
    op.create_index(op.f('ix_organizations_slug'), 'organizations', ['slug'], unique=True)
    op.create_table('audit_logs',
    sa.Column('org_id', sa.String(length=36), nullable=False),
    sa.Column('actor_id', sa.String(length=255), nullable=False),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('entity_type', sa.String(length=100), nullable=False),
    sa.Column('entity_id', sa.String(length=255), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_id'), 'audit_logs', ['id'], unique=False)
    op.create_index(op.f('ix_audit_logs_org_id'), 'audit_logs', ['org_id'], unique=False)
    op.create_index('ix_audit_logs_org_timestamp', 'audit_logs', ['org_id', 'timestamp'], unique=False)
    op.create_index(op.f('ix_audit_logs_timestamp'), 'audit_logs', ['timestamp'], unique=False)
    op.create_table('cloud_accounts',
    sa.Column('org_id', sa.String(length=36), nullable=False),
    sa.Column('provider_type', sa.String(length=50), nullable=False),
    sa.Column('account_id', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('org_id', 'provider_type', 'account_id', name='uq_account_org_provider_account_id')
    )
    op.create_index(op.f('ix_cloud_accounts_id'), 'cloud_accounts', ['id'], unique=False)
    op.create_index(op.f('ix_cloud_accounts_org_id'), 'cloud_accounts', ['org_id'], unique=False)
    op.create_index('ix_cloud_accounts_org_status', 'cloud_accounts', ['org_id', 'status'], unique=False)
    op.create_table('integrations',
    sa.Column('org_id', sa.String(length=36), nullable=False),
    sa.Column('provider_type', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('auth_method', sa.String(length=50), nullable=False),
    sa.Column('config_json', sa.JSON(), nullable=True),
    sa.Column('last_sync_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_integrations_id'), 'integrations', ['id'], unique=False)
    op.create_index(op.f('ix_integrations_org_id'), 'integrations', ['org_id'], unique=False)
    op.create_index('ix_integrations_org_provider', 'integrations', ['org_id', 'provider_type'], unique=False)
    op.create_table('scenarios',
    sa.Column('org_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=1000), nullable=True),
    sa.Column('baseline_monthly_cost', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('projected_monthly_cost', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('monthly_savings', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('percentage_savings', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.Column('performance_risk', sa.String(length=20), nullable=False),
    sa.Column('reliability_risk', sa.String(length=20), nullable=False),
    sa.Column('complexity_level', sa.String(length=20), nullable=False),
    sa.Column('assumptions_json', sa.JSON(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scenarios_id'), 'scenarios', ['id'], unique=False)
    op.create_index('ix_scenarios_org_created', 'scenarios', ['org_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_scenarios_org_id'), 'scenarios', ['org_id'], unique=False)
    op.create_table('cloud_resources',
    sa.Column('account_id', sa.String(length=36), nullable=False),
    sa.Column('region_id', sa.String(length=36), nullable=True),
    sa.Column('service_name', sa.String(length=100), nullable=False),
    sa.Column('resource_type', sa.String(length=100), nullable=False),
    sa.Column('resource_arn', sa.String(length=500), nullable=True),
    sa.Column('native_id', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('specs_json', sa.JSON(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['cloud_accounts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['region_id'], ['cloud_regions.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('account_id', 'native_id', name='uq_resource_account_native_id')
    )
    op.create_index(op.f('ix_cloud_resources_account_id'), 'cloud_resources', ['account_id'], unique=False)
    op.create_index(op.f('ix_cloud_resources_id'), 'cloud_resources', ['id'], unique=False)
    op.create_index(op.f('ix_cloud_resources_region_id'), 'cloud_resources', ['region_id'], unique=False)
    op.create_index(op.f('ix_cloud_resources_resource_arn'), 'cloud_resources', ['resource_arn'], unique=False)
    op.create_index('ix_resources_account_service_type', 'cloud_resources', ['account_id', 'service_name', 'resource_type'], unique=False)
    op.create_table('cost_snapshots',
    sa.Column('account_id', sa.String(length=36), nullable=False),
    sa.Column('period_start', sa.Date(), nullable=False),
    sa.Column('period_end', sa.Date(), nullable=False),
    sa.Column('period_type', sa.String(length=20), nullable=False),
    sa.Column('total_cost', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('breakdown_json', sa.JSON(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['cloud_accounts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cost_snapshots_account_id'), 'cost_snapshots', ['account_id'], unique=False)
    op.create_index('ix_cost_snapshots_account_period', 'cost_snapshots', ['account_id', 'period_start', 'period_type'], unique=False)
    op.create_index(op.f('ix_cost_snapshots_id'), 'cost_snapshots', ['id'], unique=False)
    op.create_index(op.f('ix_cost_snapshots_period_start'), 'cost_snapshots', ['period_start'], unique=False)
    op.create_table('forecasts',
    sa.Column('account_id', sa.String(length=36), nullable=False),
    sa.Column('forecast_month', sa.Date(), nullable=False),
    sa.Column('projected_cost', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('lower_bound', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('upper_bound', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('confidence_pct', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('cost_drivers_json', sa.JSON(), nullable=False),
    sa.Column('algorithm', sa.String(length=50), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['cloud_accounts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('account_id', 'forecast_month', name='uq_forecast_account_month')
    )
    op.create_index(op.f('ix_forecasts_account_id'), 'forecasts', ['account_id'], unique=False)
    op.create_index('ix_forecasts_account_month', 'forecasts', ['account_id', 'forecast_month'], unique=False)
    op.create_index(op.f('ix_forecasts_forecast_month'), 'forecasts', ['forecast_month'], unique=False)
    op.create_index(op.f('ix_forecasts_id'), 'forecasts', ['id'], unique=False)
    op.create_table('sync_jobs',
    sa.Column('integration_id', sa.String(length=36), nullable=False),
    sa.Column('account_id', sa.String(length=36), nullable=True),
    sa.Column('job_type', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('records_synced', sa.Integer(), nullable=False),
    sa.Column('error_message', sa.String(length=1000), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['cloud_accounts.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['integration_id'], ['integrations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sync_jobs_account_id'), 'sync_jobs', ['account_id'], unique=False)
    op.create_index(op.f('ix_sync_jobs_id'), 'sync_jobs', ['id'], unique=False)
    op.create_index(op.f('ix_sync_jobs_integration_id'), 'sync_jobs', ['integration_id'], unique=False)
    op.create_index('ix_sync_jobs_status_started', 'sync_jobs', ['status', 'started_at'], unique=False)
    op.create_table('anomalies',
    sa.Column('account_id', sa.String(length=36), nullable=False),
    sa.Column('resource_id', sa.String(length=36), nullable=True),
    sa.Column('service_name', sa.String(length=100), nullable=False),
    sa.Column('observed_cost', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('baseline_cost', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('percentage_change', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.Column('detected_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('detection_rule', sa.String(length=100), nullable=False),
    sa.Column('observed_metrics_json', sa.JSON(), nullable=True),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('inferred_cause', sa.String(length=500), nullable=True),
    sa.Column('confidence_pct', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('inference_details_json', sa.JSON(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['cloud_accounts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['resource_id'], ['cloud_resources.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_anomalies_account_detected', 'anomalies', ['account_id', 'detected_at'], unique=False)
    op.create_index(op.f('ix_anomalies_account_id'), 'anomalies', ['account_id'], unique=False)
    op.create_index('ix_anomalies_account_severity_status', 'anomalies', ['account_id', 'severity', 'status'], unique=False)
    op.create_index(op.f('ix_anomalies_detected_at'), 'anomalies', ['detected_at'], unique=False)
    op.create_index(op.f('ix_anomalies_id'), 'anomalies', ['id'], unique=False)
    op.create_index(op.f('ix_anomalies_resource_id'), 'anomalies', ['resource_id'], unique=False)
    op.create_index(op.f('ix_anomalies_service_name'), 'anomalies', ['service_name'], unique=False)
    op.create_table('cost_records',
    sa.Column('account_id', sa.String(length=36), nullable=False),
    sa.Column('resource_id', sa.String(length=36), nullable=True),
    sa.Column('service_name', sa.String(length=100), nullable=False),
    sa.Column('usage_date', sa.Date(), nullable=False),
    sa.Column('unblended_cost', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('amortized_cost', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('usage_quantity', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('usage_unit', sa.String(length=50), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['cloud_accounts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['resource_id'], ['cloud_resources.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_cost_records_account_date_service', 'cost_records', ['account_id', 'usage_date', 'service_name'], unique=False)
    op.create_index(op.f('ix_cost_records_account_id'), 'cost_records', ['account_id'], unique=False)
    op.create_index(op.f('ix_cost_records_id'), 'cost_records', ['id'], unique=False)
    op.create_index('ix_cost_records_resource_date', 'cost_records', ['resource_id', 'usage_date'], unique=False)
    op.create_index(op.f('ix_cost_records_resource_id'), 'cost_records', ['resource_id'], unique=False)
    op.create_index(op.f('ix_cost_records_service_name'), 'cost_records', ['service_name'], unique=False)
    op.create_index(op.f('ix_cost_records_usage_date'), 'cost_records', ['usage_date'], unique=False)
    op.create_table('optimization_opportunities',
    sa.Column('account_id', sa.String(length=36), nullable=False),
    sa.Column('resource_id', sa.String(length=36), nullable=True),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('waste_type', sa.String(length=100), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('estimated_waste_monthly', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('evidence_json', sa.JSON(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['cloud_accounts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['resource_id'], ['cloud_resources.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_opportunities_account_status', 'optimization_opportunities', ['account_id', 'status'], unique=False)
    op.create_index(op.f('ix_optimization_opportunities_account_id'), 'optimization_opportunities', ['account_id'], unique=False)
    op.create_index(op.f('ix_optimization_opportunities_category'), 'optimization_opportunities', ['category'], unique=False)
    op.create_index(op.f('ix_optimization_opportunities_id'), 'optimization_opportunities', ['id'], unique=False)
    op.create_index(op.f('ix_optimization_opportunities_resource_id'), 'optimization_opportunities', ['resource_id'], unique=False)
    op.create_table('scenario_changes',
    sa.Column('scenario_id', sa.String(length=36), nullable=False),
    sa.Column('resource_id', sa.String(length=36), nullable=True),
    sa.Column('change_type', sa.String(length=50), nullable=False),
    sa.Column('current_spec', sa.String(length=500), nullable=False),
    sa.Column('proposed_spec', sa.String(length=500), nullable=False),
    sa.Column('delta_cost', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['resource_id'], ['cloud_resources.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['scenario_id'], ['scenarios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scenario_changes_id'), 'scenario_changes', ['id'], unique=False)
    op.create_index(op.f('ix_scenario_changes_resource_id'), 'scenario_changes', ['resource_id'], unique=False)
    op.create_index(op.f('ix_scenario_changes_scenario_id'), 'scenario_changes', ['scenario_id'], unique=False)
    op.create_index('ix_scenario_changes_scenario_resource', 'scenario_changes', ['scenario_id', 'resource_id'], unique=False)
    op.create_table('tags',
    sa.Column('resource_id', sa.String(length=36), nullable=False),
    sa.Column('key', sa.String(length=255), nullable=False),
    sa.Column('value', sa.String(length=1000), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['resource_id'], ['cloud_resources.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('resource_id', 'key', name='uq_resource_tag_key')
    )
    op.create_index(op.f('ix_tags_id'), 'tags', ['id'], unique=False)
    op.create_index('ix_tags_key_value', 'tags', ['key', 'value'], unique=False)
    op.create_index(op.f('ix_tags_resource_id'), 'tags', ['resource_id'], unique=False)
    op.create_table('recommendations',
    sa.Column('opportunity_id', sa.String(length=36), nullable=False),
    sa.Column('resource_id', sa.String(length=36), nullable=True),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('current_configuration', sa.String(length=500), nullable=False),
    sa.Column('recommended_configuration', sa.String(length=500), nullable=False),
    sa.Column('estimated_monthly_savings', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('estimated_annual_savings', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('confidence_pct', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('risk_level', sa.String(length=20), nullable=False),
    sa.Column('reasoning', sa.String(length=1000), nullable=False),
    sa.Column('evidence_json', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['opportunity_id'], ['optimization_opportunities.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['resource_id'], ['cloud_resources.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recommendations_category'), 'recommendations', ['category'], unique=False)
    op.create_index('ix_recommendations_category_risk', 'recommendations', ['category', 'risk_level'], unique=False)
    op.create_index(op.f('ix_recommendations_id'), 'recommendations', ['id'], unique=False)
    op.create_index('ix_recommendations_opp_status', 'recommendations', ['opportunity_id', 'status'], unique=False)
    op.create_index(op.f('ix_recommendations_opportunity_id'), 'recommendations', ['opportunity_id'], unique=False)
    op.create_index(op.f('ix_recommendations_resource_id'), 'recommendations', ['resource_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_recommendations_resource_id'), table_name='recommendations')
    op.drop_index(op.f('ix_recommendations_opportunity_id'), table_name='recommendations')
    op.drop_index('ix_recommendations_opp_status', table_name='recommendations')
    op.drop_index(op.f('ix_recommendations_id'), table_name='recommendations')
    op.drop_index('ix_recommendations_category_risk', table_name='recommendations')
    op.drop_index(op.f('ix_recommendations_category'), table_name='recommendations')
    op.drop_table('recommendations')
    op.drop_index(op.f('ix_tags_resource_id'), table_name='tags')
    op.drop_index('ix_tags_key_value', table_name='tags')
    op.drop_index(op.f('ix_tags_id'), table_name='tags')
    op.drop_table('tags')
    op.drop_index('ix_scenario_changes_scenario_resource', table_name='scenario_changes')
    op.drop_index(op.f('ix_scenario_changes_scenario_id'), table_name='scenario_changes')
    op.drop_index(op.f('ix_scenario_changes_resource_id'), table_name='scenario_changes')
    op.drop_index(op.f('ix_scenario_changes_id'), table_name='scenario_changes')
    op.drop_table('scenario_changes')
    op.drop_index(op.f('ix_optimization_opportunities_resource_id'), table_name='optimization_opportunities')
    op.drop_index(op.f('ix_optimization_opportunities_id'), table_name='optimization_opportunities')
    op.drop_index(op.f('ix_optimization_opportunities_category'), table_name='optimization_opportunities')
    op.drop_index(op.f('ix_optimization_opportunities_account_id'), table_name='optimization_opportunities')
    op.drop_index('ix_opportunities_account_status', table_name='optimization_opportunities')
    op.drop_table('optimization_opportunities')
    op.drop_index(op.f('ix_cost_records_usage_date'), table_name='cost_records')
    op.drop_index(op.f('ix_cost_records_service_name'), table_name='cost_records')
    op.drop_index(op.f('ix_cost_records_resource_id'), table_name='cost_records')
    op.drop_index('ix_cost_records_resource_date', table_name='cost_records')
    op.drop_index(op.f('ix_cost_records_id'), table_name='cost_records')
    op.drop_index(op.f('ix_cost_records_account_id'), table_name='cost_records')
    op.drop_index('ix_cost_records_account_date_service', table_name='cost_records')
    op.drop_table('cost_records')
    op.drop_index(op.f('ix_anomalies_service_name'), table_name='anomalies')
    op.drop_index(op.f('ix_anomalies_resource_id'), table_name='anomalies')
    op.drop_index(op.f('ix_anomalies_id'), table_name='anomalies')
    op.drop_index(op.f('ix_anomalies_detected_at'), table_name='anomalies')
    op.drop_index('ix_anomalies_account_severity_status', table_name='anomalies')
    op.drop_index(op.f('ix_anomalies_account_id'), table_name='anomalies')
    op.drop_index('ix_anomalies_account_detected', table_name='anomalies')
    op.drop_table('anomalies')
    op.drop_index('ix_sync_jobs_status_started', table_name='sync_jobs')
    op.drop_index(op.f('ix_sync_jobs_integration_id'), table_name='sync_jobs')
    op.drop_index(op.f('ix_sync_jobs_id'), table_name='sync_jobs')
    op.drop_index(op.f('ix_sync_jobs_account_id'), table_name='sync_jobs')
    op.drop_table('sync_jobs')
    op.drop_index(op.f('ix_forecasts_id'), table_name='forecasts')
    op.drop_index(op.f('ix_forecasts_forecast_month'), table_name='forecasts')
    op.drop_index('ix_forecasts_account_month', table_name='forecasts')
    op.drop_index(op.f('ix_forecasts_account_id'), table_name='forecasts')
    op.drop_table('forecasts')
    op.drop_index(op.f('ix_cost_snapshots_period_start'), table_name='cost_snapshots')
    op.drop_index(op.f('ix_cost_snapshots_id'), table_name='cost_snapshots')
    op.drop_index('ix_cost_snapshots_account_period', table_name='cost_snapshots')
    op.drop_index(op.f('ix_cost_snapshots_account_id'), table_name='cost_snapshots')
    op.drop_table('cost_snapshots')
    op.drop_index('ix_resources_account_service_type', table_name='cloud_resources')
    op.drop_index(op.f('ix_cloud_resources_resource_arn'), table_name='cloud_resources')
    op.drop_index(op.f('ix_cloud_resources_region_id'), table_name='cloud_resources')
    op.drop_index(op.f('ix_cloud_resources_id'), table_name='cloud_resources')
    op.drop_index(op.f('ix_cloud_resources_account_id'), table_name='cloud_resources')
    op.drop_table('cloud_resources')
    op.drop_index(op.f('ix_scenarios_org_id'), table_name='scenarios')
    op.drop_index('ix_scenarios_org_created', table_name='scenarios')
    op.drop_index(op.f('ix_scenarios_id'), table_name='scenarios')
    op.drop_table('scenarios')
    op.drop_index('ix_integrations_org_provider', table_name='integrations')
    op.drop_index(op.f('ix_integrations_org_id'), table_name='integrations')
    op.drop_index(op.f('ix_integrations_id'), table_name='integrations')
    op.drop_table('integrations')
    op.drop_index('ix_cloud_accounts_org_status', table_name='cloud_accounts')
    op.drop_index(op.f('ix_cloud_accounts_org_id'), table_name='cloud_accounts')
    op.drop_index(op.f('ix_cloud_accounts_id'), table_name='cloud_accounts')
    op.drop_table('cloud_accounts')
    op.drop_index(op.f('ix_audit_logs_timestamp'), table_name='audit_logs')
    op.drop_index('ix_audit_logs_org_timestamp', table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_org_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_id'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_organizations_slug'), table_name='organizations')
    op.drop_index(op.f('ix_organizations_id'), table_name='organizations')
    op.drop_table('organizations')
    op.drop_index(op.f('ix_cloud_regions_id'), table_name='cloud_regions')
    op.drop_table('cloud_regions')
    # ### end Alembic commands ###
